version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - power-usage-net
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Kolkata
    container_name: server
    working_dir: /home/apps/power-usage/
    volumes:
      - ~/Developer/Projects/Node/power-usage:/home/apps/power-usage
      - node_modules:/home/apps/power-usage/node_modules
    depends_on:
      postgres_db:
        condition: service_started
      redis_db:
        condition: service_started
    command: npm start

  postgres_db:
    image: postgres
    networks:
      - power-usage-net
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/Developer/dbs/postgres:/var/lib/postgresql/data

  redis_db:
    image: redis:latest
    networks:
      - power-usage-net
    container_name: redis_db
    volumes:
      - ~/Developer/dbs/redis:/data
    ports:
      - 6379:6379

networks:
  power-usage-net:

volumes:
  node_modules:
